### ISSUE TITLE
extend to link object

### ISSUE THREAD

**Issue by tomkralidis** [stac-extensions/file#1]
We would like to display file properties not only for assets but for links as well.

As a user I would like to see file sizes for given assets and links so that I can determine download strategies visually.

**Comment by m-mohr** [comment]
Links are usually not meant to be downloaded (automatically), instead downloadable things are usually in assets. Nevertheless, I could see some use cases here and we are happy to accept PRs.

**Comment by tomkralidis** [comment]
PR for consideration in #9
