### ISSUE TITLE
add a language property 

### ISSUE THREAD

**Issue by p1d1d1** [stac-extensions/file#12]
For some datasets in our catalog, we provide asset files in different languages. In our current implementation (e.g.  https://radiantearth.github.io/stac-browser/#/external/data.geo.admin.ch/api/stac/v0.9/collections/ch.bav.haltestellen-oev/items/haltestellen-oev?.asset=asset-haltestellen-oev_2056_de.csv.zip) we are using an extension to provide the "lang" info at asset level.
By the way we think that the file extension would be the right place for that, something like "file:lang".
What do you think? Would you consider to add "lang" to the file extension?

**Comment by m-mohr** [comment]
Charset for textfiles would be a file attribute, but I don't think the language itself is really a "file" attribute so I think language could be a separate extension itself. This could simply be based on what OGC APIs define: http://docs.ogc.org/DRAFTS/20-004.html#collections-properties-table (i.e. a `language` property). Long-term I could see this also being added to STAC common metadata, honestly. Maybe it would be worth opening an issue in stac-spec itself about the addition of language to common metadata.

PS: I'm likely working on a "multilanguage" STAC API extension soon so there might also be coming something out of that (although in an HTTP context usually you do it via headers): https://github.com/radiantearth/stac-api-spec/issues/306

**Comment by p1d1d1** [comment]
@m-mohr as far as I can see, the `language` property if for the metadata (title, description, ...). 
Here we need something really at file level. We want to communicate to the user the language in which any textual information in the file is expressed.
PS: we use STAC also for vector data !

**Comment by m-mohr** [comment]
@p1d1d1 If we'd add "language" to the STAC common metadata it would be applicable to different contexts, comparable to "created" and updated" for example:
- language in Item properties / Collection -> metadata language
- language in assets -> file langauge
- language in links -> language of what is linked to
- ...
