### ISSUE TITLE
mapping object to go in raster or its own extension?

### ISSUE THREAD

**Issue by cholmes** [stac-extensions/file#6]
It looks like we took out most of the raster fields, but the 'mapping object' seems to be an advanced raster thing - I think it tells you what different values of pixels actually mean? It doesn't seem like a generic 'file' thing. It perhaps could go in its own extension, but I think it's confusing in the file extension.

**Comment by m-mohr** [comment]
I planned to transfer the field to https://github.com/stac-extensions/classification, but I doubt I'll get to it in the next months.

**Comment by m-mohr** [comment]
See also the discussions in https://github.com/stac-extensions/raster/issues/17

**Comment by m-mohr** [comment]
I think the best idea would be to deprecate file:values here once classification is out, but still leave it in for a while as this is already used in a couple of applications and the field specs may be a bit different in complexity.
